{{- if and .Values.rbac.create .Values.serviceAccount.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "airflow.fullname" . }}-uid50000
subjects:
- kind: ServiceAccount
  name: {{ include "airflow.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ template "airflow.fullname" . }}-uid50000
{{- end -}}
